services:
  mysql:
    image: mysql:8.0
    container_name: droplite-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: droplite_db
      MYSQL_USER: droplite_user
      MYSQL_PASSWORD: droplite_password
    ports:
      - "3306:3306"
    networks:
      - droplite-network
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"  # S3-compatible API
      - "9090:9090"  # MinIO Web UI (Console)
    environment:
      MINIO_ROOT_USER: droplite_user
      MINIO_ROOT_PASSWORD: droplite_password
    command: server /data --console-address ":9090"
    networks:
      - droplite-network
    volumes:
      - minio-data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 5

  ui:
    build: ./droplite-client
    container_name: droplite-ui
    ports:
      - "80:80"
    networks:
      - droplite-network

  eureka:
    build:
      context: ./droplite-server
      dockerfile: ./discovery-server/Dockerfile
    container_name: droplite-eureka
    ports:
      - "8761:8761"
    networks:
      - droplite-network

  gateway:
    build:
      context: ./droplite-server
      dockerfile: ./gateway-service/Dockerfile
    container_name: droplite-gateway
    ports:
      - "8080:8080"
    networks:
      - droplite-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://droplite-eureka:8761/eureka/

  auth:
    build:
      context: ./droplite-server
      dockerfile: ./auth-service/Dockerfile
    container_name: droplite-auth
    ports:
      - "8001:8001"
    networks:
      - droplite-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://droplite-eureka:8761/eureka/

  users:
    build:
      context: ./droplite-server
      dockerfile: ./user-service/Dockerfile
    container_name: droplite-users
    ports:
      - "8002:8002"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - droplite-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://droplite-eureka:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/droplite_db

  server:
    build:
      context: ./droplite-server
      dockerfile: ./core-service/Dockerfile
    container_name: droplite-server
    ports:
      - "8003:8003"
    depends_on:
      mysql:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - droplite-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://droplite-eureka:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/droplite_db

networks:
  droplite-network:
    driver: bridge

volumes:
  mysql-data:
  minio-data: