security:
  jwt:
    secret-key: GlG4YF/5EQKJ44SaJtHEd//VJeffEZ0OUCYOKm/TYow=
    expire-in: 43200000 #12 hours in milli

server:
  port: 8001

spring:
  application:
    name: auth-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

api:
  url:
    user: http://user-service/user